### request
POST http://localhost:4004/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "testuser@test.com",
  "password": "password123"
}

> {%
  client.global.set("token", response.body.token);
%}
